server:
  port: 7001


user:
  name: GB
  age: 25
  phone: 13669274050

spring:
  datasource:
    url: jdbc:mysql://119.23.223.206:3306/demo?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: mysql
    password: gb931011...
    driver-class-name: com.mysql.jdbc.Driver